CREATE DATABASE IF NOT EXISTS `ozon_selection`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `ozon_selection`;

CREATE TABLE IF NOT EXISTS `seed_skus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(32) NOT NULL,
  `source` VARCHAR(64) NOT NULL DEFAULT 'manual',
  `status` ENUM('pending','qualified','rejected','done','failed') NOT NULL DEFAULT 'pending',
  `score` DECIMAL(12,4) NULL,
  `reason` VARCHAR(512) NULL,
  `last_checked_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_seed_sku` (`sku`),
  KEY `idx_seed_status` (`status`, `last_checked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sku_products` (
  `sku` VARCHAR(32) NOT NULL,
  `variant_id` VARCHAR(32) NULL,
  `product_url` VARCHAR(1024) NULL,
  `title` VARCHAR(512) NULL,
  `brand` VARCHAR(255) NULL,
  `category` VARCHAR(512) NULL,
  `category_ids` JSON NULL,
  `price` DECIMAL(18,4) NULL,
  `original_price` DECIMAL(18,4) NULL,
  `card_price` DECIMAL(18,4) NULL,
  `currency` VARCHAR(16) NULL,
  `main_image_url` VARCHAR(2048) NULL,
  `image_urls` JSON NULL,
  `rfbs_leq_1500` DECIMAL(10,4) NULL,
  `rfbs_leq_5000` DECIMAL(10,4) NULL,
  `rfbs_gt_5000` DECIMAL(10,4) NULL,
  `fbp_leq_1500` DECIMAL(10,4) NULL,
  `fbp_leq_5000` DECIMAL(10,4) NULL,
  `fbp_gt_5000` DECIMAL(10,4) NULL,
  `sold_count` INT NULL,
  `sold_sum_text` VARCHAR(128) NULL,
  `sold_sum_rub` DECIMAL(18,4) NULL,
  `sold_sum_cny` DECIMAL(18,4) NULL,
  `avg_orders_on_acc_days` DECIMAL(18,4) NULL,
  `avg_gmv_on_acc_days` DECIMAL(18,4) NULL,
  `avg_gmv_on_acc_days_cny` DECIMAL(18,4) NULL,
  `sales_dynamics` DECIMAL(18,4) NULL,
  `drr` DECIMAL(10,4) NULL,
  `days_in_promo` INT NULL,
  `discount` DECIMAL(10,4) NULL,
  `promo_revenue_share` DECIMAL(10,4) NULL,
  `days_with_trafarets` INT NULL,
  `qty_view_pdp` INT NULL,
  `session_count_search` INT NULL,
  `conv_to_cart_pdp` DECIMAL(10,4) NULL,
  `conv_to_cart_search` DECIMAL(10,4) NULL,
  `conv_view_to_order` DECIMAL(10,4) NULL,
  `sales_schema` VARCHAR(128) NULL,
  `nullable_redemption_rate` DECIMAL(10,4) NULL,
  `custom_click_rate_text` VARCHAR(64) NULL,
  `custom_click_rate` DECIMAL(10,4) NULL,
  `custom_volume_text` VARCHAR(128) NULL,
  `custom_weight_text` VARCHAR(64) NULL,
  `custom_weight_g` DECIMAL(18,4) NULL,
  `nullable_create_date_text` VARCHAR(128) NULL,
  `create_days` INT NULL,
  `status_update_sales` TINYINT(1) NOT NULL DEFAULT 0,
  `status_update_variant` TINYINT(1) NOT NULL DEFAULT 0,
  `status_version` INT NULL,
  `maozi_fields_zh_json` JSON NULL,
  `raw_maozi_json` JSON NULL,
  `raw_frontend_json` JSON NULL,
  `maozi_collected_at` DATETIME NULL,
  `first_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sku`),
  KEY `idx_product_category` (`category`(128)),
  KEY `idx_product_brand` (`brand`),
  KEY `idx_product_sold_count` (`sold_count`),
  KEY `idx_product_sold_sum_cny` (`sold_sum_cny`),
  KEY `idx_product_create_days` (`create_days`),
  KEY `idx_product_weight_g` (`custom_weight_g`),
  KEY `idx_product_sales_schema` (`sales_schema`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sku_plugin_metrics` (
  `sku` VARCHAR(32) NOT NULL,
  `variant_id` VARCHAR(32) NULL,
  `brand` VARCHAR(255) NULL,
  `category` VARCHAR(512) NULL,
  `category_ids` JSON NULL,
  `rfbs_leq_1500` DECIMAL(10,4) NULL,
  `rfbs_leq_5000` DECIMAL(10,4) NULL,
  `rfbs_gt_5000` DECIMAL(10,4) NULL,
  `fbp_leq_1500` DECIMAL(10,4) NULL,
  `fbp_leq_5000` DECIMAL(10,4) NULL,
  `fbp_gt_5000` DECIMAL(10,4) NULL,
  `sold_count` INT NULL,
  `sold_sum_text` VARCHAR(128) NULL,
  `sold_sum_rub` DECIMAL(18,4) NULL,
  `sold_sum_cny` DECIMAL(18,4) NULL,
  `avg_orders_on_acc_days` DECIMAL(18,4) NULL,
  `avg_gmv_on_acc_days` DECIMAL(18,4) NULL,
  `avg_gmv_on_acc_days_cny` DECIMAL(18,4) NULL,
  `sales_dynamics` DECIMAL(18,4) NULL,
  `drr` DECIMAL(10,4) NULL,
  `days_in_promo` INT NULL,
  `discount` DECIMAL(10,4) NULL,
  `promo_revenue_share` DECIMAL(10,4) NULL,
  `days_with_trafarets` INT NULL,
  `qty_view_pdp` INT NULL,
  `conv_to_cart_pdp` DECIMAL(10,4) NULL,
  `session_count_search` INT NULL,
  `conv_to_cart_search` DECIMAL(10,4) NULL,
  `conv_view_to_order` DECIMAL(10,4) NULL,
  `sales_schema` VARCHAR(128) NULL,
  `nullable_redemption_rate` DECIMAL(10,4) NULL,
  `custom_click_rate_text` VARCHAR(64) NULL,
  `custom_click_rate` DECIMAL(10,4) NULL,
  `custom_volume_text` VARCHAR(128) NULL,
  `custom_weight_text` VARCHAR(64) NULL,
  `custom_weight_g` DECIMAL(18,4) NULL,
  `nullable_create_date_text` VARCHAR(128) NULL,
  `create_days` INT NULL,
  `status_update_sales` TINYINT(1) NOT NULL DEFAULT 0,
  `status_update_variant` TINYINT(1) NOT NULL DEFAULT 0,
  `status_version` INT NULL,
  `raw_json` JSON NULL,
  `collected_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sku`),
  KEY `idx_metrics_category` (`category`(128)),
  KEY `idx_metrics_brand` (`brand`),
  KEY `idx_metrics_sold_count` (`sold_count`),
  KEY `idx_metrics_sold_sum_cny` (`sold_sum_cny`),
  KEY `idx_metrics_collected_at` (`collected_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `seller_shops` (
  `seller_key` CHAR(40) NOT NULL,
  `name` VARCHAR(255) NULL,
  `home_url` VARCHAR(1024) NOT NULL,
  `logo_url` VARCHAR(2048) NULL,
  `last_collected_at` DATETIME NULL,
  `next_collect_after` DATETIME NULL,
  `raw_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`seller_key`),
  UNIQUE KEY `uk_seller_home_url` (`home_url`(512)),
  KEY `idx_seller_next_collect` (`next_collect_after`),
  KEY `idx_seller_last_collected` (`last_collected_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `seller_offers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_sku` VARCHAR(32) NOT NULL,
  `seller_key` CHAR(40) NOT NULL,
  `offer_sku` VARCHAR(32) NULL,
  `seller_name` VARCHAR(255) NULL,
  `seller_home_url` VARCHAR(1024) NULL,
  `offer_product_url` VARCHAR(1024) NULL,
  `price_text` VARCHAR(128) NULL,
  `price_amount` DECIMAL(18,4) NULL,
  `currency` VARCHAR(16) NULL,
  `main_image_url` VARCHAR(2048) NULL,
  `raw_json` JSON NULL,
  `collected_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_offer` (`source_sku`, `seller_key`, `offer_sku`),
  KEY `idx_offer_seller` (`seller_key`),
  KEY `idx_offer_sku` (`offer_sku`),
  KEY `idx_offer_price` (`price_amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `seller_home_skus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seller_key` CHAR(40) NOT NULL,
  `sku` VARCHAR(32) NOT NULL,
  `product_url` VARCHAR(1024) NULL,
  `title` VARCHAR(512) NULL,
  `price_amount` DECIMAL(18,4) NULL,
  `currency` VARCHAR(16) NULL,
  `main_image_url` VARCHAR(2048) NULL,
  `raw_json` JSON NULL,
  `discovered_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_seller_sku` (`seller_key`, `sku`),
  KEY `idx_home_sku` (`sku`),
  KEY `idx_home_discovered` (`discovered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `crawl_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_type` ENUM('sku3','seller_offers','seller_home','playwright_refresh') NOT NULL,
  `task_key` VARCHAR(255) NOT NULL,
  `payload` JSON NULL,
  `status` ENUM('pending','running','success','failed','skipped') NOT NULL DEFAULT 'pending',
  `priority` INT NOT NULL DEFAULT 100,
  `run_after` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `locked_by` VARCHAR(128) NULL,
  `locked_at` DATETIME NULL,
  `attempts` INT NOT NULL DEFAULT 0,
  `max_attempts` INT NOT NULL DEFAULT 3,
  `last_error` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_key` (`task_key`),
  KEY `idx_task_pick` (`status`, `run_after`, `priority`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `crawl_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT UNSIGNED NULL,
  `worker_id` VARCHAR(128) NULL,
  `level` ENUM('info','warning','error') NOT NULL DEFAULT 'info',
  `message` TEXT NULL,
  `context_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_log_task` (`task_id`),
  KEY `idx_log_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `top_list_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `query_key` CHAR(40) NOT NULL,
  `main_type` VARCHAR(32) NOT NULL,
  `filters_json` JSON NOT NULL,
  `page_from` INT NOT NULL,
  `page_to` INT NOT NULL,
  `page_size` INT NOT NULL,
  `status` ENUM('running','success','failed') NOT NULL DEFAULT 'running',
  `pages_fetched` INT NOT NULL DEFAULT 0,
  `items_fetched` INT NOT NULL DEFAULT 0,
  `due_skus` INT NOT NULL DEFAULT 0,
  `processed_skus` INT NOT NULL DEFAULT 0,
  `qualified_skus` INT NOT NULL DEFAULT 0,
  `rejected_skus` INT NOT NULL DEFAULT 0,
  `seller_expansions` INT NOT NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_top_list_run_recent` (`query_key`, `started_at`),
  KEY `idx_top_list_run_status` (`status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `top_list_skus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `query_key` CHAR(40) NOT NULL,
  `run_id` BIGINT UNSIGNED NULL,
  `sku` VARCHAR(32) NOT NULL,
  `page_no` INT NOT NULL,
  `page_rank` INT NOT NULL,
  `name` VARCHAR(512) NULL,
  `brand` VARCHAR(255) NULL,
  `link` VARCHAR(1024) NULL,
  `photo` VARCHAR(2048) NULL,
  `cate1` VARCHAR(255) NULL,
  `cate2` VARCHAR(255) NULL,
  `cate3` VARCHAR(255) NULL,
  `sold_count` INT NULL,
  `sold_sum` DECIMAL(18,4) NULL,
  `avg_price` DECIMAL(18,4) NULL,
  `sales_dynamics` DECIMAL(18,4) NULL,
  `conv_to_cart_pdp` DECIMAL(18,4) NULL,
  `conv_to_cart_search` DECIMAL(18,4) NULL,
  `conv_view_to_order` DECIMAL(18,4) NULL,
  `qty_view_pdp` INT NULL,
  `views` INT NULL,
  `avg_delivery_days` DECIMAL(18,4) NULL,
  `volume` DECIMAL(18,4) NULL,
  `weight` DECIMAL(18,4) NULL,
  `seller_id` VARCHAR(64) NULL,
  `sales_schema` VARCHAR(64) NULL,
  `is_china` TINYINT(1) NOT NULL DEFAULT 0,
  `blocked_by_seller` TINYINT(1) NOT NULL DEFAULT 0,
  `nullable_create_date` DATE NULL,
  `upstream_update_time` DATE NULL,
  `snapshot_hash` CHAR(40) NOT NULL,
  `last_processed_snapshot_hash` CHAR(40) NULL,
  `last_process_status` VARCHAR(32) NULL,
  `last_process_reason` VARCHAR(512) NULL,
  `last_selected_at` DATETIME NULL,
  `last_processed_at` DATETIME NULL,
  `raw_json` JSON NULL,
  `first_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_top_list_query_sku` (`query_key`, `sku`),
  KEY `idx_top_list_rank` (`query_key`, `page_no`, `page_rank`),
  KEY `idx_top_list_processed` (`query_key`, `last_processed_at`),
  KEY `idx_top_list_update_time` (`upstream_update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
