USE `ozon_selection`;

CREATE TABLE IF NOT EXISTS `seed_pool_skus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_type` VARCHAR(32) NOT NULL DEFAULT 'top_list',
  `query_key` CHAR(40) NOT NULL,
  `source_run_id` BIGINT UNSIGNED NULL,
  `sku` VARCHAR(32) NOT NULL,
  `page_no` INT NOT NULL,
  `page_rank` INT NOT NULL,
  `name` VARCHAR(512) NULL,
  `brand` VARCHAR(255) NULL,
  `link` VARCHAR(1024) NULL,
  `photo` VARCHAR(2048) NULL,
  `cate1` VARCHAR(255) NULL,
  `cate2` VARCHAR(255) NULL,
  `cate3` VARCHAR(255) NULL,
  `sold_count` INT NULL,
  `sold_sum` DECIMAL(18,4) NULL,
  `avg_price` DECIMAL(18,4) NULL,
  `sales_dynamics` DECIMAL(18,4) NULL,
  `conv_to_cart_pdp` DECIMAL(18,4) NULL,
  `conv_to_cart_search` DECIMAL(18,4) NULL,
  `conv_view_to_order` DECIMAL(18,4) NULL,
  `qty_view_pdp` INT NULL,
  `views` INT NULL,
  `avg_delivery_days` DECIMAL(18,4) NULL,
  `volume` DECIMAL(18,4) NULL,
  `weight` DECIMAL(18,4) NULL,
  `seller_id` VARCHAR(64) NULL,
  `sales_schema` VARCHAR(64) NULL,
  `is_china` TINYINT(1) NOT NULL DEFAULT 0,
  `blocked_by_seller` TINYINT(1) NOT NULL DEFAULT 0,
  `nullable_create_date` DATE NULL,
  `upstream_update_time` DATE NULL,
  `snapshot_hash` CHAR(40) NOT NULL,
  `last_processed_snapshot_hash` CHAR(40) NULL,
  `last_process_status` VARCHAR(32) NULL,
  `last_process_reason` VARCHAR(512) NULL,
  `last_offer_count` INT NULL,
  `last_selected_at` DATETIME NULL,
  `last_processed_at` DATETIME NULL,
  `raw_json` JSON NULL,
  `first_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_seed_pool_source_query_sku` (`source_type`, `query_key`, `sku`),
  KEY `idx_seed_pool_rank` (`source_type`, `query_key`, `page_no`, `page_rank`),
  KEY `idx_seed_pool_processed` (`source_type`, `query_key`, `last_processed_at`),
  KEY `idx_seed_pool_status` (`source_type`, `query_key`, `last_process_status`, `last_processed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `seed_pool_skus`
  (`source_type`, `query_key`, `source_run_id`, `sku`, `page_no`, `page_rank`, `name`, `brand`, `link`, `photo`,
   `cate1`, `cate2`, `cate3`, `sold_count`, `sold_sum`, `avg_price`, `sales_dynamics`,
   `conv_to_cart_pdp`, `conv_to_cart_search`, `conv_view_to_order`, `qty_view_pdp`,
   `views`, `avg_delivery_days`, `volume`, `weight`, `seller_id`, `sales_schema`,
   `is_china`, `blocked_by_seller`, `nullable_create_date`, `upstream_update_time`,
   `snapshot_hash`, `raw_json`, `first_seen_at`, `last_seen_at`)
SELECT
  'top_list', `query_key`, `run_id`, `sku`, `page_no`, `page_rank`, `name`, `brand`, `link`, `photo`,
  `cate1`, `cate2`, `cate3`, `sold_count`, `sold_sum`, `avg_price`, `sales_dynamics`,
  `conv_to_cart_pdp`, `conv_to_cart_search`, `conv_view_to_order`, `qty_view_pdp`,
  `views`, `avg_delivery_days`, `volume`, `weight`, `seller_id`, `sales_schema`,
  `is_china`, `blocked_by_seller`, `nullable_create_date`, `upstream_update_time`,
  `snapshot_hash`, `raw_json`, `first_seen_at`, `last_seen_at`
FROM `top_list_skus`;
