USE `ozon_selection`;

CREATE TABLE IF NOT EXISTS `sku_universe` (
  `sku` VARCHAR(32) NOT NULL,
  `variant_id` VARCHAR(32) NULL,
  `title` VARCHAR(512) NULL,
  `brand` VARCHAR(255) NULL,
  `category` VARCHAR(512) NULL,
  `category_ids` JSON NULL,
  `rfbs_leq_1500` DECIMAL(10,4) NULL,
  `rfbs_leq_5000` DECIMAL(10,4) NULL,
  `rfbs_gt_5000` DECIMAL(10,4) NULL,
  `fbp_leq_1500` DECIMAL(10,4) NULL,
  `fbp_leq_5000` DECIMAL(10,4) NULL,
  `fbp_gt_5000` DECIMAL(10,4) NULL,
  `product_url` VARCHAR(1024) NULL,
  `main_image_url` VARCHAR(2048) NULL,
  `price_amount` DECIMAL(18,4) NULL,
  `price_currency` VARCHAR(16) NULL,
  `price_cny` DECIMAL(18,4) NULL,
  `seller_offer_count` INT NULL,
  `sold_count` INT NULL,
  `sold_sum_text` VARCHAR(128) NULL,
  `sold_sum_rub` DECIMAL(18,4) NULL,
  `sold_sum_cny` DECIMAL(18,4) NULL,
  `avg_orders_on_acc_days` DECIMAL(18,4) NULL,
  `avg_gmv_on_acc_days` DECIMAL(18,4) NULL,
  `avg_gmv_on_acc_days_cny` DECIMAL(18,4) NULL,
  `sales_dynamics` DECIMAL(18,4) NULL,
  `drr` DECIMAL(10,4) NULL,
  `days_in_promo` INT NULL,
  `discount` DECIMAL(10,4) NULL,
  `promo_revenue_share` DECIMAL(10,4) NULL,
  `days_with_trafarets` INT NULL,
  `qty_view_pdp` INT NULL,
  `conv_to_cart_pdp` DECIMAL(10,4) NULL,
  `session_count_search` INT NULL,
  `conv_to_cart_search` DECIMAL(10,4) NULL,
  `conv_view_to_order` DECIMAL(10,4) NULL,
  `sales_schema` VARCHAR(128) NULL,
  `nullable_redemption_rate` DECIMAL(10,4) NULL,
  `custom_click_rate_text` VARCHAR(64) NULL,
  `custom_click_rate` DECIMAL(10,4) NULL,
  `custom_volume_text` VARCHAR(128) NULL,
  `custom_weight_text` VARCHAR(64) NULL,
  `custom_weight_g` DECIMAL(18,4) NULL,
  `nullable_create_date_text` VARCHAR(128) NULL,
  `create_days` INT NULL,
  `status_update_sales` TINYINT(1) NOT NULL DEFAULT 0,
  `status_update_variant` TINYINT(1) NOT NULL DEFAULT 0,
  `status_version` INT NULL,
  `is_formal_qualified` TINYINT(1) NOT NULL DEFAULT 0,
  `formal_rule_name` VARCHAR(128) NULL,
  `formal_rule_reason` VARCHAR(512) NULL,
  `is_seed_qualified` TINYINT(1) NULL,
  `seed_rule_name` VARCHAR(128) NULL,
  `seed_rule_reason` VARCHAR(512) NULL,
  `maozi_fields_zh_json` JSON NULL,
  `maozi_raw_json` JSON NULL,
  `product_raw_json` JSON NULL,
  `plugin_card_raw_json` JSON NULL,
  `seller_offers_json` JSON NULL,
  `first_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_maozi_collected_at` DATETIME NULL,
  `last_product_collected_at` DATETIME NULL,
  `last_plugin_collected_at` DATETIME NULL,
  `last_offer_collected_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sku`),
  KEY `idx_universe_formal` (`is_formal_qualified`, `last_seen_at`),
  KEY `idx_universe_seed` (`is_seed_qualified`, `last_seen_at`),
  KEY `idx_universe_brand` (`brand`),
  KEY `idx_universe_sold_count` (`sold_count`),
  KEY `idx_universe_offer_count` (`seller_offer_count`),
  KEY `idx_universe_seen` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sku_discovery_sources` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(32) NOT NULL,
  `source_type` VARCHAR(32) NOT NULL,
  `source_key` VARCHAR(255) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_name` VARCHAR(255) NULL,
  `related_sku` VARCHAR(32) NULL,
  `source_rank` INT NULL,
  `raw_json` JSON NULL,
  `first_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_discovery_source` (`sku`, `source_type`, `source_key`),
  KEY `idx_discovery_type` (`source_type`, `last_seen_at`),
  KEY `idx_discovery_related` (`related_sku`),
  KEY `idx_discovery_sku` (`sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
