CREATE DATABASE IF NOT EXISTS `ozon_selection`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `ozon_selection`;

CREATE TABLE IF NOT EXISTS `matched_source_products` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NULL,
  `source_image_path` VARCHAR(1024) NULL,
  `source_image_file` VARCHAR(255) NULL,
  `source_image_url` VARCHAR(2048) NULL,
  `source_image_hash` CHAR(64) NULL,
  `source_image_size_bytes` BIGINT UNSIGNED NULL,
  `source_image_width` INT NULL,
  `source_image_height` INT NULL,
  `source_image_mime` VARCHAR(64) NULL,
  `search_url` VARCHAR(2048) NULL,
  `search_image_id` VARCHAR(64) NULL,
  `search_image_id_list` VARCHAR(255) NULL,
  `search_offer_tags` VARCHAR(255) NULL,
  `search_sort_type` VARCHAR(64) NULL,
  `matched_rank` INT NOT NULL DEFAULT 0,
  `matched_score` DECIMAL(18,8) NULL,
  `matched_title` VARCHAR(512) NULL,
  `matched_offer_id` VARCHAR(64) NULL,
  `matched_product_url` VARCHAR(2048) NULL,
  `matched_main_image_url` VARCHAR(2048) NULL,
  `matched_shop_name` VARCHAR(255) NULL,
  `matched_shop_uid` VARCHAR(255) NULL,
  `matched_shop_years_text` VARCHAR(64) NULL,
  `matched_price_text` VARCHAR(128) NULL,
  `matched_price_amount` DECIMAL(18,4) NULL,
  `matched_currency` VARCHAR(16) NULL,
  `matched_sales_text` VARCHAR(128) NULL,
  `matched_min_order_text` VARCHAR(128) NULL,
  `matched_services_json` JSON NULL,
  `matched_tags_json` JSON NULL,
  `matched_attributes_json` JSON NULL,
  `matched_card_raw_json` JSON NULL,
  `matched_detail_raw_json` JSON NULL,
  `matched_detail_url` VARCHAR(2048) NULL,
  `match_status` ENUM('pending','matched','no_result','error') NOT NULL DEFAULT 'pending',
  `match_reason` VARCHAR(512) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_rank` (`sku`, `matched_rank`),
  KEY `idx_status` (`match_status`),
  KEY `idx_offer_id` (`matched_offer_id`),
  KEY `idx_sku` (`sku`),
  KEY `idx_image_hash` (`source_image_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `matched_source_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `run_key` CHAR(40) NOT NULL,
  `chrome_profile_dir` VARCHAR(1024) NULL,
  `chrome_executable_path` VARCHAR(1024) NULL,
  `chrome_channel` VARCHAR(32) NULL,
  `chrome_remote_debugging_port` INT NULL,
  `image_input_dir` VARCHAR(1024) NOT NULL,
  `download_dir` VARCHAR(1024) NOT NULL,
  `status` ENUM('running','success','failed') NOT NULL DEFAULT 'running',
  `source_count` INT NOT NULL DEFAULT 0,
  `matched_count` INT NOT NULL DEFAULT 0,
  `failed_count` INT NOT NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_run_key` (`run_key`),
  KEY `idx_status_started` (`status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
